CREATE TABLE ff(id INTEGER PRIMARY KEY, name TEXT, age INTEGER);
INSERT INTO ff VALUES(1,'Sharan',11);
INSERT INTO ff VALUES(2,'Sajiv',40);
INSERT INTO ff VALUES(3,'Anu',36);
INSERT INTO ff VALUES(4,'Jahnvi',7);
SELECT * FROM ff;
